### ISSUE TITLE
download dir + schedule

### ISSUE THREAD

**Issue by c64bob** [vayan/beetsync#1]
Hi, I was looking exactly for an app like this, thanks for taking the time to write it! 

Would it be possible to make the download directory configurable? Also, would it be possible to automatically download new songs once every 24 hours or so?

Thanks again!

**Comment by vayan** [comment]
Hi ! 

My app is pretty buggy right now, I tried to make it work with a 3000+ music library and it killed my phone every time, I know the devs behind beets are going to release a new and better web api so I'm waiting on that to do a rewrite of this app.

When I do I'll make sure to add custom directory ! Automatic download is more complicated :/ 

Cheers

**Comment by c64bob** [comment]
Gotcha. Thanks for the update
